project:
  type: website
  output-dir: docs

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: practice.qmd
        text: Irrelevant
      - href: Analysis1.qmd
        text: Eliot's Mileage

format:
  html:
    theme: flatly
    include-in-header: verify.html
    include-after-body: my_footer.html
    
    
# cd ~/Desktop/Bens-Website
#quarto render
#git add .
#git commit -m "describe your changes"
#git push



